# Generated by Django 5.0.7 on 2024-07-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='upload/')),
                ('secret_key', models.CharField(max_length=4)),
                ('date_time', models.CharField(max_length=10)),
            ],
        ),
    ]
